version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      day: saturday
      time: '09:00'
      timezone: 'Europe/Madrid'
    open-pull-requests-limit: 10
    groups:
      vitest:
        patterns:
          - 'vitest'
          - '@vitest/*'
      eslint-plugins: # TODO Add eslint back once updated to v9
        patterns:
          - '@shlinkio/eslint-config-js-coding-standard'
          - 'typescript-eslint'
          - '*eslint-plugin*'
